export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT = "LOGOUT";

export const REGISTER="REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const EXISTING_USER = "EXISTING_USER";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const RESET_EMAIL_STATUS = "RESET_EMAIL_STATUS";
export const RESET_CODE_VALIDATION = "RESET_CODE_VALIDATION";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";